### ISSUE TITLE
jqlang release v1.7 breaks packtivity

### ISSUE THREAD

**Issue by matthewfeickert** [yadage/packtivity#96]
`jq` (the language) had its first release in 5 years with [`jq` `v1.7`](https://github.com/jqlang/jq/releases/tag/jq-1.7), which includes some breaking changes.

`jq` the Python library [added support for `jqlang` `v1.7` in `jq` `v1.6.0`](https://github.com/mwilliamson/jq.py/compare/1.5.0...1.6.0) and so `v1.6.0` is also a breaking change for `packtivity`.

## Action plan

* [x] Add a cap on
https://github.com/yadage/packtivity/blob/fdeab4bab5f520237d034ff4689aff9e41f97d9e/setup.py#L14

of `<1.6.0`
   - c.f. https://github.com/yadage/packtivity/pull/97
* [x] Release `packtivity` `v0.16.1` with this cap in it.
   - The `jq` capped `packtivity` will get picked up by the `yadage` ecosystem and subsequently keep other breaks from happening
   - c.f. https://github.com/yadage/packtivity/releases/tag/v0.16.1
* [x] Find a way to fix `packtivity` to work with both `jqlang` `v1.7` and before.
   - c.f. https://github.com/yadage/packtivity/pull/99
* [x] Make a new `packtivity` `v0.16.2` that adds this support and removes the cap.
   - c.f. https://github.com/yadage/packtivity/releases/tag/v0.16.2
* [x] Yank `packtivity` `v0.16.1` from PyPI.
   - c.f. https://pypi.org/project/packtivity/0.16.1/

**Comment by matthewfeickert** [comment]
cc @kratsg in the event that similar things hit any of your libraries.

**Comment by kratsg** [comment]
what actually breaks?

**Comment by matthewfeickert** [comment]
Here's an example failure for

https://github.com/yadage/packtivity/blob/69aadb944ab3b759712a1885f1f76abf08562c4a/tests/test_asyncbackends.py#L9-L20

```pytb
=================================== FAILURES ===================================
________________________________ test_multiproc ________________________________

tmpdir = local('/tmp/pytest-of-runner/pytest-0/test_multiproc0')
basic_localfs_state = <LocalFSState rw: ['/tmp/pytest-of-runner/pytest-0/test_multiproc0'], ro: []>
localproc_packspec = {'environment': {'environment_type': 'localproc-env'}, 'process': {'cmd': 'echo Hello World > {outputfile}', 'process_type': 'string-interpolated-cmd'}, 'publisher': {'outputmap': {'output': 'outputfile'}, 'publisher_type': 'frompar-pub'}}

    def test_multiproc(tmpdir, basic_localfs_state, localproc_packspec):
        basic_localfs_state.ensure()
        pars = pdm.create({"outputfile": "{workdir}/helloworld.txt"})
        backend = MultiProcBackend(2)
        proxy = backend.submit(localproc_packspec, pars, basic_localfs_state)
        while not backend.ready(proxy):
            pass
>       assert backend.successful(proxy)
E       assert False
E        +  where False = <bound method MultiProcBackend.successful of <packtivity.asyncbackends.MultiProcBackend object at 0x7f68c3a[77](https://github.com/yadage/packtivity/actions/runs/6211558623/job/16860874815#step:6:78)160>>(<packtivity.asyncbackends.PacktivityProxyBase object at 0x7f68c3a1b4c0>)
E        +    where <bound method MultiProcBackend.successful of <packtivity.asyncbackends.MultiProcBackend object at 0x7f68c3a77160>> = <packtivity.asyncbackends.MultiProcBackend object at 0x7f68c3a77160>.successful

tests/test_asyncbackends.py:16: AssertionError
----------------------------- Captured stderr call -----------------------------
2023-09-17 04:27:26,0[86](https://github.com/yadage/packtivity/actions/runs/6211558623/job/16860874815#step:6:87) | pack.packtivity.step |   INFO | starting file logging for topic: step
_________________________________ test_maincli _________________________________

tmpdir = local('/tmp/pytest-of-runner/pytest-0/test_maincli0')

    def test_maincli(tmpdir):
        runner = CliRunner()
        result = runner.invoke(
            packtivity.cli.runcli,
            [
                "tests/testspecs/localtouchfile.yml",
                "-p",
                'outputfile="{workdir}/hello.txt"',
                "-w",
                str(tmpdir),
            ],
        )
>       assert result.exit_code == 0
E       AssertionError: assert 1 == 0
E        +  where 1 = <Result ValueError('jq: error: leaf_paths/0 is not defined at <top-level>, line 1:\nleaf_paths\njq: 1 compile error')>.exit_code
```

This kind of

```
jq: error: leaf_paths/0 is not defined at <top-level>, line 1:\nleaf_paths\njq: 1 compile error
```

is happening everywhere.

**Comment by matthewfeickert** [comment]
I think it might be something like https://github.com/jqlang/jq/issues/38#issuecomment-9770240

**Comment by matthewfeickert** [comment]
Ah, this would do it from https://github.com/jqlang/jq/releases/tag/jq-1.7:

> Remove deprecated filters `leaf_paths`, `recurse_down`. `@itchyny` https://github.com/jqlang/jq/pull/2666

given that `leaf_paths` is used in `packtivity`.

**Comment by matthewfeickert** [comment]
Closing as resolved with https://github.com/yadage/packtivity/releases/tag/v0.16.2
